### ISSUE TITLE
meet this error:fast_rcnn_loc_loss:0.0

### ISSUE THREAD

**Issue by FakerYFX** [yangJirui/RRPN_FPN_Tensorflow#10]
meet this error:fast_rcnn_loc_loss:0.0.can any one helpp me?
@yangJirui

**Comment by yangJirui** [comment]
sry, i dont have time to fix bugs for this repository recently, please refer our another repository : :  https://github.com/DetectionTeamUCAS/RRPN_Faster-RCNN_Tensorflow.git which is
RRPN based on Faster-RCNN.
